version: "3"
services:
    mongo:
        image: mongo
        ports:
            - 27018:27017 # 27018 to prevent conflicts with local mongodb
        volumes:
            - mongo:/data/db
    api:
        container_name: rx_code_challenge_api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        ports:
            - 5000:80
        environment: 
            MONGO_URI: mongodb://mongo:27017/rx_code_challenge
        
volumes:
    mongo:
